print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay!Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print('我爱瓜瓜')
#i love gua gua
print('我想瓜瓜')
print('干嘛呢？瓜瓜')
#print('a')